### ISSUE TITLE
Why has two color display before?

### ISSUE THREAD

**Issue by qrqhuang** [mallowigi/color-highlighter#73]
This line has just one color being defined, but why has two color display before.
I can't figure out what does it meaning...

![image](https://user-images.githubusercontent.com/17166063/179371036-69ea320d-b2fa-4305-b890-33cc1bd77a3b.png)

**Comment by mallowigi** [comment]
I'm not sure 100% but it could be because one is from the plugin and the other one from another setting?

**Comment by qrqhuang** [comment]
> I'm not sure 100% but it could be because one is from the plugin and the other one from another setting?

As this plugin page describe with `JAVA` lang, it also displays two element.

![image](https://user-images.githubusercontent.com/17166063/179401310-244188a7-cdc2-444a-87c7-327130268aef.png)

So it will not be another setting, may be.

**Comment by haosmos** [comment]
same here 

phpsorm: 222.3345.61
color highlighter: 11.0.0

![GWSL_vcxsrv_8e7bWCLANd](https://user-images.githubusercontent.com/30666874/180494061-08aae3a0-2ab3-4164-a0bd-51675415d9f3.png)

**Comment by mallowigi** [comment]
I see. The problem was because it applies the highlighter twice: one for the language, and one for the fallback if it applies. I'll fix this.

**Comment by mallowigi** [comment]
Fixed in 12.0

**Comment by FlorentLM** [comment]
Still having this issue with Python and the latest version of color-highlighter
